---
title: "Data Cleaning"
output: 
  html_document:
    toc: true
    toc_float: true
---
```{r message=FALSE, echo=FALSE}
library(tidyverse)
library(readr)
```

### Student Weight Data
```{r message=FALSE}
Student_Weight = read_csv("data/Student Weight.csv")
```

```{r}
Student_Weight  = 
  Student_Weight |>
  janitor::clean_names() |>
  rename('district'='location_code') |>
  filter(year_reported %in% c("2014-2015", "2015-2016", "2016-2017", "2017-2018", "2018-2019"))
```

```{r}
Student_Weight$year_reported = sub(".*-", "", Student_Weight$year_reported)

Student_Weight = 
  Student_Weight |>
  mutate(year_reported = as.numeric(Student_Weight$year_reported)) |>
  filter(grade_level!="DISTRICT TOTAL" & sex!="ALL")
```

```{r message=FALSE}
Student_Weight = Student_Weight |> filter(year_reported==2019 & county!='STATEWIDE (EXCLUDING NYC)') |> select(-region, -area_name)
```

```{r}
Student_Weight |> group_by(county)
```

```{r}
show_student_weight = 
  Student_Weight |>
  head(5) |>
  knitr::kable(digits = 3)
```

```{r}
show_student_weight
```

Description and what we did: xxxxx

### Demographics Data
```{r message=FALSE}
Demographics_all = read_csv("data/Demographics_all.csv")
```

```{r message=FALSE}
Demographics_all = 
  Demographics_all |> 
  janitor::clean_names() |>
  mutate(district = as.numeric(district)) |>
  filter(year==2019)

Demographics_all
```

### Join Demographics with Student Weight
```{r message=FALSE}
result = merge(Student_Weight, Demographics_all, by = "district")|>
  select(-num_free_lunch, -num_reduced_lunch, -num_ell) |>
  drop_na()

head(result)
```


```{r}
write.csv(result, file = "result_2019.csv", row.names = FALSE)
```


