<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regression</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Project_report.html">Project Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="data_cleaning.html">Data Cleaning</a>
</li>
<li>
  <a href="visualization.html">Visualization</a>
</li>
<li>
  <a href="regression.html">Regression &amp; T-Test</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="https://github.com/cara-dong/nyweight.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Regression</h1>

</div>


<div id="two-sample-t-test" class="section level2">
<h2>Two sample t-test</h2>
<div id="t-test-for-means-in-sex-groups" class="section level3">
<h3>T-test for Means in Sex Groups</h3>
<p>First, we need to check for normality assumptions.</p>
<pre class="r"><code>normality_check1 = cleaned_data |&gt;
  filter(sex==&quot;FEMALE&quot;) |&gt;
  ggplot(aes(x = number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Female Number Overweight&quot;)

normality_check2 = cleaned_data |&gt;
  filter(sex==&quot;MALE&quot;) |&gt;
  ggplot(aes(x = number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Male Number Overweight&quot;)

normality_check3 = cleaned_data |&gt;
  filter(grade_level==&quot;ELEMENTARY&quot;) |&gt;
  ggplot(aes(x = number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Elementary Number Overweight&quot;)

normality_check4 = cleaned_data |&gt;
  filter(grade_level==&quot;MIDDLE/HIGH&quot;) |&gt;
  ggplot(aes(x = number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Middle/High Number Overweight&quot;)

combined_plot = normality_check1 + normality_check2 + normality_check3 + normality_check4 

combined_plot_layout = combined_plot + 
  plot_layout(ncol = 2, nrow = 2)

combined_plot_layout</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>From the histogram, the number of overweight students in four groups
are all right-skewed, so we need to perform a log transformation before
testing. Here are the distributions after transformation.</p>
<pre class="r"><code>t_test_data = cleaned_data |&gt;
  mutate(log_number_overweight = log(number_overweight + 1))

normality_check1 = t_test_data |&gt;
  filter(sex==&quot;FEMALE&quot;) |&gt;
  ggplot(aes(x = log_number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Log Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Log Female Number Overweight&quot;)

normality_check2 = t_test_data |&gt;
  filter(sex==&quot;MALE&quot;) |&gt;
  ggplot(aes(x = log_number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Log Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Log Male Number Overweight&quot;)

normality_check3 = t_test_data |&gt;
  filter(grade_level==&quot;ELEMENTARY&quot;) |&gt;
  ggplot(aes(x = log_number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Log Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Log Elementary Number Overweight&quot;)

normality_check4 = t_test_data |&gt;
  filter(grade_level==&quot;MIDDLE/HIGH&quot;) |&gt;
  ggplot(aes(x = log_number_overweight), theme(plot.margin = unit(c(1, 1, 1, 1), &quot;lines&quot;))) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Log Number Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Log Middle/High Number Overweight&quot;)

combined_plot = normality_check1 + normality_check2 + normality_check3 + normality_check4 

combined_plot_layout = combined_plot + 
  plot_layout(ncol = 2, nrow = 2)

combined_plot_layout</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Now, the distributions look roughly normal.</p>
<p>Check equality of variance:</p>
<p>Test for Equality of Variances by Sex</p>
<pre class="r"><code>t_test_data |&gt; 
  levene_test(log_number_overweight ~ sex) |&gt;
  knitr::kable(title = &quot;Test for Equality of Variances by Sex&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
df1
</th>
<th style="text-align:right;">
df2
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4798
</td>
<td style="text-align:right;">
1.916216
</td>
<td style="text-align:right;">
0.1663388
</td>
</tr>
</tbody>
</table>
<p>Test for Equality of Variances by Grade Level</p>
<pre class="r"><code>t_test_data |&gt; 
  levene_test(log_number_overweight ~ grade_level) |&gt; 
  knitr::kable(title=&quot;Test for Equality of Variances by Grade Level&quot;)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:right;">
df1
</th>
<th style="text-align:right;">
df2
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4798
</td>
<td style="text-align:right;">
0.5853365
</td>
<td style="text-align:right;">
0.4442658
</td>
</tr>
</tbody>
</table>
<p>Since the p-values for both are not significant, we will use
independent t-test with equal variance.</p>
<p>We want to conduct a two-sample t-test to compare the average number
of overweight female students across two different educational levels:
elementary and middle/high school.</p>
<pre class="r"><code>female_data = t_test_data[t_test_data$sex == &#39;FEMALE&#39;, ]

elementary_data = female_data[female_data$grade_level == &#39;ELEMENTARY&#39;, &#39;log_number_overweight&#39;]
middle_high_data = female_data[female_data$grade_level == &#39;MIDDLE/HIGH&#39;, &#39;log_number_overweight&#39;]

t_test_result = t.test(elementary_data, middle_high_data, var.equal = TRUE)

print(t_test_result)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  elementary_data and middle_high_data
## t = 5.8472, df = 2390, p-value = 5.684e-09
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.1259737 0.2531050
## sample estimates:
## mean of x mean of y 
##  3.435272  3.245732</code></pre>
<p>The test results suggest that there is a statistically significant
difference in the mean log number of female overweight students between
elementary and middle/high schools, with elementary schools having a
higher mean on the log scale, given the very low p-value and the
confidence interval that does not include zero.</p>
<p>Next, we conduct a two-sample t-test to compare the average number of
overweight male students across two different educational levels:
elementary and middle/high school.</p>
<pre class="r"><code>male_data = t_test_data[t_test_data$sex == &#39;MALE&#39;, ]

elementary_data = male_data[male_data$grade_level == &#39;ELEMENTARY&#39;, &#39;log_number_overweight&#39;]
middle_high_data = male_data[male_data$grade_level == &#39;MIDDLE/HIGH&#39;, &#39;log_number_overweight&#39;]

t_test_result = t.test(elementary_data, middle_high_data, var.equal = TRUE)

print(t_test_result)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  elementary_data and middle_high_data
## t = 7.368, df = 2406, p-value = 2.367e-13
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.1773483 0.3059834
## sample estimates:
## mean of x mean of y 
##  3.437084  3.195418</code></pre>
<p>There is a statistically significant difference between the mean log
number of male overweight students in elementary schools compared to
middle/high schools, with elementary schools having a higher mean on the
log scale, given the 2.367e-13 low p-value and the confidence interval
that does not include zero.</p>
</div>
<div id="t-test-for-means-in-grade-level" class="section level3">
<h3>T-test for Means in Grade Level</h3>
<p>Next, we conduct a two-sample t-test to compare the average number of
overweight elementary students across two different sex groups: male and
female.</p>
<pre class="r"><code>elementary = t_test_data[t_test_data$grade_level == &#39;ELEMENTARY&#39;, ]

male = elementary[elementary$sex == &#39;MALE&#39;, &#39;log_number_overweight&#39;]
female = elementary[elementary$sex == &#39;FEMALE&#39;, &#39;log_number_overweight&#39;]

t_test_result = t.test(male, female, var.equal = TRUE)

print(t_test_result)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  male and female
## t = 0.055614, df = 2479, p-value = 0.9557
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.06210400  0.06572951
## sample estimates:
## mean of x mean of y 
##  3.437084  3.435272</code></pre>
<p>The t-test results suggest that there is no significant difference in
the mean log number of overweight students in elementary school students
between male and female sex groups, given that p-value 0.9557 is greater
than 0.05 at 95% confidence level. The means are nearly identical, and
the statistical analysis does not provide evidence of a meaningful
disparity.</p>
<p>Then, we conduct a two-sample t-test to compare the average number of
overweight middle/high school students across two different sex groups:
male and female.</p>
<pre class="r"><code>elementary = t_test_data[t_test_data$grade_level == &#39;MIDDLE/HIGH&#39;, ]

male = elementary[elementary$sex == &#39;MALE&#39;, &#39;log_number_overweight&#39;]
female = elementary[elementary$sex == &#39;FEMALE&#39;, &#39;log_number_overweight&#39;]

t_test_result = t.test(male, female, var.equal = TRUE)

print(t_test_result)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  male and female
## t = -1.5459, df = 2317, p-value = 0.1223
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.11413683  0.01350927
## sample estimates:
## mean of x mean of y 
##  3.195418  3.245732</code></pre>
<p>The t-test results also suggest that there is no significant
difference in the mean log number of overweight students in middle/high
school students between male and female sex groups, given that p-value
0.1223 is greater than 0.05 at 95% confidence level.</p>
</div>
</div>
<div id="regression" class="section level2">
<h2>Regression</h2>
<div id="slr---sex-vs-percentage-of-overweight" class="section level3">
<h3>SLR - Sex vs Percentage of Overweight</h3>
<pre class="r"><code>train_data  = 
  cleaned_data |&gt;
  select(year, sex, grade_level, 
         number_overweight, percent_overweight,
         number_obese, percent_obese, 
         number_overweight_or_obese, percent_overweight_or_obese,
         number_healthy_weight, percent_healthy_weight) |&gt;
  mutate(sex = ifelse(sex==&quot;FEMALE&quot;, 0, 1), 
         grade_level = ifelse(grade_level==&quot;ELEMENTARY&quot;, 0, 1)) |&gt;
  drop_na()</code></pre>
<p>Check if outcome is normally distributed.</p>
<pre class="r"><code>school_level_dist = train_data |&gt;
  ggplot(aes(x = percent_overweight)) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Percent Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Distribution of Percent Overweight at Finer School Level&quot;)

ggplotly(school_level_dist)</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ad1776556747b034d56f" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-ad1776556747b034d56f">{"x":{"data":[{"orientation":"v","width":[2.0965517241379308,2.0965517241379317,2.0965517241379299,2.0965517241379317,2.0965517241379317,2.0965517241379317,2.0965517241379317,2.0965517241379317,2.0965517241379317,2.0965517241379317,2.0965517241379246,2.0965517241379317,2.0965517241379317,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246,2.0965517241379246],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[2.0965517241379308,4.1931034482758616,6.2896551724137924,8.3862068965517231,10.482758620689655,12.579310344827586,14.675862068965515,16.772413793103446,18.868965517241378,20.96551724137931,23.062068965517241,25.158620689655169,27.255172413793101,29.351724137931029,31.448275862068961,33.544827586206893,35.641379310344817,37.737931034482756,39.83448275862068,41.931034482758619,44.027586206896544,46.124137931034468,48.220689655172407,50.317241379310332,52.41379310344827,54.510344827586195,56.606896551724134,58.703448275862058,60.799999999999983,62.896551724137922],"y":[2,2,15,93,271,619,967,1061,794,483,232,111,62,36,19,17,6,5,1,1,0,1,1,0,0,0,0,0,0,1],"text":["count:    2<br />percent_overweight:  2.096552","count:    2<br />percent_overweight:  4.193103","count:   15<br />percent_overweight:  6.289655","count:   93<br />percent_overweight:  8.386207","count:  271<br />percent_overweight: 10.482759","count:  619<br />percent_overweight: 12.579310","count:  967<br />percent_overweight: 14.675862","count: 1061<br />percent_overweight: 16.772414","count:  794<br />percent_overweight: 18.868966","count:  483<br />percent_overweight: 20.965517","count:  232<br />percent_overweight: 23.062069","count:  111<br />percent_overweight: 25.158621","count:   62<br />percent_overweight: 27.255172","count:   36<br />percent_overweight: 29.351724","count:   19<br />percent_overweight: 31.448276","count:   17<br />percent_overweight: 33.544828","count:    6<br />percent_overweight: 35.641379","count:    5<br />percent_overweight: 37.737931","count:    1<br />percent_overweight: 39.834483","count:    1<br />percent_overweight: 41.931034","count:    0<br />percent_overweight: 44.027586","count:    1<br />percent_overweight: 46.124138","count:    1<br />percent_overweight: 48.220690","count:    0<br />percent_overweight: 50.317241","count:    0<br />percent_overweight: 52.413793","count:    0<br />percent_overweight: 54.510345","count:    0<br />percent_overweight: 56.606897","count:    0<br />percent_overweight: 58.703448","count:    0<br />percent_overweight: 60.800000","count:    1<br />percent_overweight: 62.896552"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(89,89,89,0.8)","line":{"width":1.8897637795275593,"color":"rgba(255,255,255,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826498,"l":43.105022831050235},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Distribution of Percent Overweight at Finer School Level","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-2.0965517241379308,67.089655172413785],"tickmode":"array","ticktext":["0","20","40","60"],"tickvals":[0,20,39.999999999999993,60],"categoryorder":"array","categoryarray":["0","20","40","60"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Percent Overweight","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-53.050000000000004,1114.05],"tickmode":"array","ticktext":["0","300","600","900"],"tickvals":[0,300,600,900],"categoryorder":"array","categoryarray":["0","300","600","900"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Count","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"b9a275c98b42":{"x":{},"type":"bar"}},"cur_data":"b9a275c98b42","visdat":{"b9a275c98b42":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>The outcome is roughly normal, so no transformation needed.</p>
<p>Check for normality of residuals.</p>
<pre class="r"><code>model1 = lm(percent_overweight ~ sex, data = train_data)
hist(resid(model1), breaks = &quot;FD&quot;, main = &quot;Histogram of Residuals&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Check for homocedasticity.</p>
<pre class="r"><code>plot(fitted(model1), resid(model1))
abline(h = 0, col = &quot;red&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The variance of the residuals is roughly constant across all levels
of the predictor and the residuals are also normally distributed. So
assumptions for linear regression are checked. We can proceed to conduct
the prediction.</p>
<p>Fit the model.</p>
<pre class="r"><code>sex_slr = lm(percent_overweight ~ sex, data = train_data) 
sex_slr_df = sex_slr |&gt; broom::tidy()

knitr::kable(sex_slr_df)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
17.546446
</td>
<td style="text-align:right;">
0.0892055
</td>
<td style="text-align:right;">
196.696951
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
sex
</td>
<td style="text-align:right;">
-1.177219
</td>
<td style="text-align:right;">
0.1259459
</td>
<td style="text-align:right;">
-9.347023
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>The SLR model we fit is percent_overweight at school-level =
17.546446 - 1.177219 * sex.</p>
<p>The coefficient estimate of -1.177219 with a p-value of almost 0
indicates that the effect of sex on the percentage of overweight
students is statistically significant.</p>
<p>Since female is encoded as the reference group 0, we can say that
male students group in NY schools had lower percentage of overweight
students compared to female students group. This corresponds to the line
plot visualization displayed in the previous section, where the line for
male students is always below that for female students.</p>
</div>
<div id="slr---grade-level-vs-percent-of-overweight"
class="section level3">
<h3>SLR - Grade Level vs Percent of Overweight</h3>
<p>Check for normality of residuals.</p>
<pre class="r"><code>model2 = lm(percent_overweight ~ grade_level, data = train_data)
hist(resid(model2), breaks = &quot;FD&quot;, main = &quot;Histogram of Residuals&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Check homosdasticity.</p>
<pre class="r"><code>plot(fitted(model2), resid(model2))
abline(h = 0, col = &quot;red&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-17-1.png" width="672" />
The variance of the residuals is roughly constant across all levels of
the predictor and the residuals are also normally distributed. So
assumptions for linear regression are checked. We can proceed to conduct
the prediction.</p>
<p>Fit the model.</p>
<pre class="r"><code>grade_level_slr = lm(percent_overweight ~ grade_level, data = train_data)
grade_level_slr_df = grade_level_slr |&gt; broom::tidy()

knitr::kable(grade_level_slr_df)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
16.126602
</td>
<td style="text-align:right;">
0.0866902
</td>
<td style="text-align:right;">
186.02569
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
grade_level
</td>
<td style="text-align:right;">
1.716477
</td>
<td style="text-align:right;">
0.1247212
</td>
<td style="text-align:right;">
13.76251
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>The SLR model we fit is percent_overweight at school-level =
16.126602 - 1.716477 * grade_level.</p>
<p>The coefficient estimate of 1.716477 with a p-value of almost 0
indicates that the effect of grade_level on the percentage of overweight
students is statistically significant.</p>
<p>Since elementary school is encoded as the reference group 0, we can
say that middle/high school students in NY had higher percentage of
overweight students compared to elementary school students. This also
corresponds to the line plot visualization displayed in the previous
section, where the line for elementary students is always below that for
middle/high school students.</p>
</div>
<div id="mlr---grade-level-sex-vs-percent-of-overweight"
class="section level3">
<h3>MLR - Grade Level &amp; Sex vs Percent of Overweight</h3>
<pre class="r"><code>mlr = lm(percent_overweight ~ grade_level + sex, data = train_data) 

mlr_df = mlr |&gt; broom::tidy()

knitr::kable(mlr_df)</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
16.717571
</td>
<td style="text-align:right;">
0.1058518
</td>
<td style="text-align:right;">
157.933676
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
grade_level
</td>
<td style="text-align:right;">
1.718086
</td>
<td style="text-align:right;">
0.1235648
</td>
<td style="text-align:right;">
13.904326
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
sex
</td>
<td style="text-align:right;">
-1.179560
</td>
<td style="text-align:right;">
0.1234951
</td>
<td style="text-align:right;">
-9.551469
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>The MLR model we fit is percent_overweight at school-level =
16.717571 - -1.179560 * grade_level + 1.718086 * grade_level.</p>
<p>The coefficient estimates with p-values of almost 0 indicates that
the effect of both sex and grade_level on the percentage of overweight
students are statistically significant.</p>
<p>Next, we use anova to check if SLR (with only sex or grade level) is
more preferrable than MLR.</p>
<pre class="r"><code>anova(sex_slr, grade_level_slr, mlr)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: percent_overweight ~ sex
## Model 2: percent_overweight ~ grade_level
## Model 3: percent_overweight ~ grade_level + sex
##   Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1   4798 91328                                  
## 2   4798 89460  0    1868.5                     
## 3   4797 87790  1    1669.6 91.231 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>So, MLR is more preferrable than SLR here because the p-value is &lt;
2.2e-16, which is significant at 5% alpha level.</p>
</div>
<div id="mlr---student-demographic-info-vs-percent-of-overweight"
class="section level3">
<h3>MLR - Student Demographic Info vs Percent of Overweight</h3>
<pre class="r"><code>selected = 
  cleaned_data |&gt;
  select(year, district, percent_overweight, num_asian, num_black, num_hisp, num_am_ind, num_white)

district_level_data = 
  selected |&gt;
  group_by(year, district) |&gt;
  summarise(med_overweight = median(percent_overweight)) |&gt;
  drop_na()</code></pre>
<pre class="r"><code>group_demo = 
  selected |&gt;
  group_by(year, district) |&gt;
  summarise(total_asian = max(num_asian), 
            total_black = max(num_black),
            total_hisp = max(num_hisp), 
            total_am_ind = max(num_am_ind), 
            total_white = max(num_white)) |&gt;
  drop_na()</code></pre>
<pre class="r"><code>result_df = 
  district_level_data |&gt; 
  left_join(group_demo, by = c(&quot;year&quot;, &quot;district&quot;)) |&gt;
  ungroup() |&gt;
  select(-district)</code></pre>
<pre class="r"><code>overweight_dist = result_df |&gt;
  ggplot(aes(x = med_overweight)) + 
  geom_histogram(alpha = 0.8, color = &quot;white&quot;) + 
  labs(
    x = &quot;Median Percent of Overweight&quot; ,
    y = &quot;Count&quot;,
    title = &quot;Distribution of Median Percent of Overweight&quot;)

ggplotly(overweight_dist)</code></pre>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-0fe277fd6749e7103118" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-0fe277fd6749e7103118">{"x":{"data":[{"orientation":"v","width":[1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896555,1.2827586206896591,1.2827586206896626,1.2827586206896626,1.2827586206896626,1.2827586206896626,1.2827586206896484,1.2827586206896626,1.2827586206896626,1.2827586206896626,1.2827586206896626,1.2827586206896626,1.2827586206896626],"base":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"x":[8.9793103448275868,10.262068965517242,11.544827586206896,12.827586206896552,14.110344827586207,15.393103448275863,16.675862068965518,17.958620689655174,19.241379310344829,20.524137931034485,21.80689655172414,23.089655172413796,24.372413793103451,25.655172413793107,26.937931034482762,28.220689655172418,29.503448275862073,30.786206896551729,32.068965517241381,33.351724137931043,34.634482758620692,35.917241379310354,37.200000000000003,38.482758620689658,39.765517241379314,41.048275862068962,42.331034482758625,43.613793103448273,44.896551724137936,46.179310344827584],"y":[8,13,30,83,154,228,276,228,107,79,30,17,12,4,3,4,2,2,1,1,1,0,0,0,0,0,0,0,0,1],"text":["count:   8<br />med_overweight:  8.97931","count:  13<br />med_overweight: 10.26207","count:  30<br />med_overweight: 11.54483","count:  83<br />med_overweight: 12.82759","count: 154<br />med_overweight: 14.11034","count: 228<br />med_overweight: 15.39310","count: 276<br />med_overweight: 16.67586","count: 228<br />med_overweight: 17.95862","count: 107<br />med_overweight: 19.24138","count:  79<br />med_overweight: 20.52414","count:  30<br />med_overweight: 21.80690","count:  17<br />med_overweight: 23.08966","count:  12<br />med_overweight: 24.37241","count:   4<br />med_overweight: 25.65517","count:   3<br />med_overweight: 26.93793","count:   4<br />med_overweight: 28.22069","count:   2<br />med_overweight: 29.50345","count:   2<br />med_overweight: 30.78621","count:   1<br />med_overweight: 32.06897","count:   1<br />med_overweight: 33.35172","count:   1<br />med_overweight: 34.63448","count:   0<br />med_overweight: 35.91724","count:   0<br />med_overweight: 37.20000","count:   0<br />med_overweight: 38.48276","count:   0<br />med_overweight: 39.76552","count:   0<br />med_overweight: 41.04828","count:   0<br />med_overweight: 42.33103","count:   0<br />med_overweight: 43.61379","count:   0<br />med_overweight: 44.89655","count:   1<br />med_overweight: 46.17931"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(89,89,89,0.8)","line":{"width":1.8897637795275593,"color":"rgba(255,255,255,1)"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826498,"l":43.105022831050235},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Distribution of Median Percent of Overweight","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[6.4137931034482758,48.744827586206895],"tickmode":"array","ticktext":["10","20","30","40"],"tickvals":[10,20,29.999999999999993,40],"categoryorder":"array","categoryarray":["10","20","30","40"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Median Percent of Overweight","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-13.800000000000001,289.80000000000001],"tickmode":"array","ticktext":["0","100","200"],"tickvals":[0,100,200],"categoryorder":"array","categoryarray":["0","100","200"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Count","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"b9a249f915ef":{"x":{},"type":"bar"}},"cur_data":"b9a249f915ef","visdat":{"b9a249f915ef":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>The outcome distribution is roughly normal, so no transformation is
needed.</p>
<p>Then, we will look at a correlation matrix to determine which
variables to select as predictors.</p>
<pre class="r"><code>cor_matrix = cor(result_df[, c(colnames(result_df))])</code></pre>
<p>We need to deal with the highly correlated predictor pairs before
fitting the model.</p>
<pre class="r"><code># Find the pairs where correlation is greater than or equal to 0.7 but less than 1
high_cor_pairs = which(cor_matrix &gt;= 0.7 &amp; cor_matrix &lt; 1, arr.ind = TRUE)

# Extract the variable names for these pairs
high_cor_var_pairs = data.frame(
  Var1 = rownames(cor_matrix)[high_cor_pairs[, 1]],
  Var2 = colnames(cor_matrix)[high_cor_pairs[, 2]],
  Correlation = cor_matrix[high_cor_pairs]
)

high_cor_var_pairs</code></pre>
<pre><code>## [1] Var1        Var2        Correlation
## &lt;0 rows&gt; (or 0-length row.names)</code></pre>
<p>There is no highly correlated pairs in all predictors. So,
multicollinearity is cleared, now we can fit an MLR model.</p>
<pre class="r"><code>mlr = lm(med_overweight ~ ., data = result_df)
display = mlr |&gt; broom::tidy() |&gt; knitr::kable()

display</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
204.6285368
</td>
<td style="text-align:right;">
119.2937283
</td>
<td style="text-align:right;">
1.715334
</td>
<td style="text-align:right;">
0.0865267
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
-0.0928606
</td>
<td style="text-align:right;">
0.0591545
</td>
<td style="text-align:right;">
-1.569797
</td>
<td style="text-align:right;">
0.1167100
</td>
</tr>
<tr>
<td style="text-align:left;">
total_asian
</td>
<td style="text-align:right;">
-0.0014845
</td>
<td style="text-align:right;">
0.0003005
</td>
<td style="text-align:right;">
-4.940426
</td>
<td style="text-align:right;">
0.0000009
</td>
</tr>
<tr>
<td style="text-align:left;">
total_black
</td>
<td style="text-align:right;">
0.0001223
</td>
<td style="text-align:right;">
0.0000984
</td>
<td style="text-align:right;">
1.242595
</td>
<td style="text-align:right;">
0.2142454
</td>
</tr>
<tr>
<td style="text-align:left;">
total_hisp
</td>
<td style="text-align:right;">
0.0002993
</td>
<td style="text-align:right;">
0.0000816
</td>
<td style="text-align:right;">
3.667092
</td>
<td style="text-align:right;">
0.0002554
</td>
</tr>
<tr>
<td style="text-align:left;">
total_am_ind
</td>
<td style="text-align:right;">
0.0037642
</td>
<td style="text-align:right;">
0.0014737
</td>
<td style="text-align:right;">
2.554306
</td>
<td style="text-align:right;">
0.0107552
</td>
</tr>
<tr>
<td style="text-align:left;">
total_white
</td>
<td style="text-align:right;">
-0.0003124
</td>
<td style="text-align:right;">
0.0000638
</td>
<td style="text-align:right;">
-4.894690
</td>
<td style="text-align:right;">
0.0000011
</td>
</tr>
</tbody>
</table>
<p>Plot residuals against fitted value</p>
<pre class="r"><code># Add predictions to the dataset
df_with_predictions = result_df |&gt;
  add_predictions(mlr, var = &quot;fitted_values&quot;)

# Add residuals to the dataset
df_with_residuals = df_with_predictions |&gt;
  add_residuals(mlr, var = &quot;residuals&quot;)

# Now plot the residuals against fitted values
ggplot(df_with_residuals, aes(x = fitted_values, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;, color = &quot;red&quot;) +
  labs(x = &quot;Fitted Values&quot;, y = &quot;Residuals&quot;, title = &quot;Residuals against Fitted Values&quot;) +
  theme_minimal()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>There is no clear pattern shown in the plot, so it is pretty
desirable. Overall, the residual plot suggests that the model has decent
prediction performance. However, the potential increase in variance
among the higher fitted values and the presence of outliers could be a
concern.</p>
<p>The model we fit is: Median Percent of Overweight at District Level =
209.229 - 0.0928606 * year - 0.0014845 * total_asian + 0.0001223 *
total_black + 0.0002993 * total_hisp + 0.0037642 * total_am_ind -
0.0003124 * total_white.</p>
<p>Except for the p-value for total_black and year, the coefficients for
all other variables are significant. Among them, the total number of
American Indian in that school district has the largest absolute value
of coefficient. So, holding all other variables constant, with one
person increase in the ethnic group of American Indians, there is a
0.0037642 percent increase in the median percent of overweight students
at district level.</p>
<p>The regression analysis indicates that demographic factors,
specifically the racial composition of students, have a statistically
significant association with the median percentage of overweight
students at the district level, as evidenced by the p-values for certain
racial groups.</p>
<p>However, the magnitude of these associations, as reflected by the
estimated coefficients, is relatively small. It is important to note
that while these effects are statistically significant for some racial
groups, the small size of the coefficients suggests that the practical
significance of these demographic variables on the median percentage of
overweight students might be limited.</p>
</div>
<div id="mlr---other-weight-status-vs-percent-of-overweight"
class="section level3">
<h3>MLR - Other Weight Status vs Percent of Overweight</h3>
<pre class="r"><code>train_data = 
  train_data |&gt; 
  select(year, percent_overweight, percent_obese, percent_overweight_or_obese, percent_healthy_weight)</code></pre>
<pre class="r"><code>mlr_weight = lm(percent_overweight ~ ., data = train_data)
display_weight = mlr_weight |&gt; broom::tidy() |&gt; knitr::kable(digits=3)

display_weight</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-2.390
</td>
<td style="text-align:right;">
1.176
</td>
<td style="text-align:right;">
-2.033
</td>
<td style="text-align:right;">
0.042
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
2.009
</td>
<td style="text-align:right;">
0.045
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_obese
</td>
<td style="text-align:right;">
-1.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
-4068.880
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_overweight_or_obese
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
2710.705
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_healthy_weight
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.035
</td>
<td style="text-align:right;">
1.121
</td>
<td style="text-align:right;">
0.262
</td>
</tr>
</tbody>
</table>
<p>Holding all other variables constant, with one percent increase in
healthy weight students, there is a 0.039 percent increase in overweight
students. However, this is not very significant as the p-value (0.262)
for the coefficient is greater than 0.05 at an 95% confidence level.</p>
</div>
<div id="mlr---lunch-type-vs-percent-of-overweight"
class="section level3">
<h3>MLR - Lunch Type vs Percent of Overweight</h3>
<p>This prediction is only available for a few years’ data because some
years do not contain the data record for free lunch and reduced
lunch.</p>
<pre class="r"><code>lunch = 
  cleaned_data |&gt; 
  filter(year %in% c(2015, 2016, 2017)) |&gt;
  group_by(year, district) |&gt;
  summarise(total_num_free_lunch = max(num_free_lunch), 
            total_num_reduced_lunch = max(num_reduced_lunch))</code></pre>
<pre class="r"><code>lunch_df = 
  district_level_data |&gt; 
  left_join(lunch, by = c(&quot;year&quot;, &quot;district&quot;)) |&gt;
  ungroup() |&gt;
  select(-district)</code></pre>
<pre class="r"><code>mlr = lm(med_overweight ~ ., data = lunch_df)
display = mlr |&gt; broom::tidy() |&gt; knitr::kable()

display</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
294.4593529
</td>
<td style="text-align:right;">
268.2056744
</td>
<td style="text-align:right;">
1.0978864
</td>
<td style="text-align:right;">
0.2725683
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
-0.1377206
</td>
<td style="text-align:right;">
0.1330457
</td>
<td style="text-align:right;">
-1.0351379
</td>
<td style="text-align:right;">
0.3009021
</td>
</tr>
<tr>
<td style="text-align:left;">
total_num_free_lunch
</td>
<td style="text-align:right;">
0.0000718
</td>
<td style="text-align:right;">
0.0000697
</td>
<td style="text-align:right;">
1.0289415
</td>
<td style="text-align:right;">
0.3038030
</td>
</tr>
<tr>
<td style="text-align:left;">
total_num_reduced_lunch
</td>
<td style="text-align:right;">
0.0001812
</td>
<td style="text-align:right;">
0.0009498
</td>
<td style="text-align:right;">
0.1907815
</td>
<td style="text-align:right;">
0.8487428
</td>
</tr>
</tbody>
</table>
<p>The model we fit is: Median Percent of Overweight at District Level =
294.4593529 - 0.1377206 * year + 0.0000718 * total_num_free_lunch +
0.0001812 * total_num_reduced_lunch.</p>
<p>We might be able to say that having more free lunch and reduced lunch
both are associated with increase in the median percent of overweight
students at school-district level.</p>
<p>However, none of the predictors included in the model show a
statistically significant relationship with the median percentage of
overweight students at the school-district level, as all p-values are
above the conventional threshold for significance (0.05).</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
